project_id = "colegio-sedes-sapientiae"

[api]
port = 54321
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[storage]
file_size_limit = "50MiB"
